author: Manolo8
main: br.com.tinycraft.arenax1.ArenaX1
name: ArenaX1
version: 0.4
commands:
  arenax1:
    aliases: [x1]
    permission: arenax1.user
  arenax1adm:
    aliases: [x1adm]
    permission: arenax1.admin
permissions:
  arenax1.user:
    default: true
  arenax1.admin:
    default: op
  